<?php
/**
 * Configuration file generated by ZF Apigility Admin
 *
 * The previous config file has been stored in ./config/modules.config.old
 */
return [
    'Zend\\Cache',
    'Zend\\Paginator',
    'Zend\\Form',
    'Zend\\InputFilter',
    'Zend\\Filter',
    'Zend\\Hydrator',
    'Zend\\Router',
    'Zend\\Validator',
    'DoctrineModule',
    'DoctrineORMModule',
    'ZF\\Versioning',
    'ZF\\ApiProblem',
    'ZF\\ContentNegotiation',
    'ZF\\Rpc',
    'ZF\\MvcAuth',
    'ZF\\Hal',
    'ZF\\Rest',
    'ZF\\ContentValidation',
    'ZF\\Apigility',
    'ZF\\Configuration',
    'ZF\\Apigility\\Documentation',
    'ZF\\HttpCache',
    'ZfrCors',
    'Application',
    'Chat',
];
