<ul id="chat" class="list-group">
</ul>

<script type="text/javascript">
    //$("#chat").load("<?php echo $this->serverUrl('/api/chat') ?>", function(response, status, xhr) {
     //   alert(response);
    $.getJSON('<?php echo $this->serverUrl('/api/chat') ?>', function(response) {
        if (response._embedded.chat.length == 0) {
            $('#chat').append($('<li>', {
                text: 'No chat messages',
                class: 'list-group-item list-group-item-dark'
            }));
        } else {
            chats = response._embedded.chat.reverse();
            $.each(chats, function (index, chat) {
                createdAt  = $('<span>', {
                    text: chat.createdAt,
                    class: 'list-group-item-text',
                });
                message  = $('<span>', {
                    text: chat.message,
                    class: 'list-group-item-text'
                });
                $('#chat').append($('<li>', {
                    class: 'list-group-item'
                }).append(createdAt).append('&nbsp;&nbsp;').append(message));
            })
        }
    }).fail(function(xhr) {
        if (xhr.status == 500) {
            alert("Cannot load chat");
        } else {
            alert("Chat not found");
        }
    });  
</script>
